- ros_topic_name: "/laser_scan"
  gz_topic_name: "/lidar2"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# PosePublisher exposes moving poses; this bridge converts them into ROS TF.
- ros_topic_name: "/tf"
  gz_topic_name: "/model/x3_lidar/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
